### ISSUE TITLE
Add output highlight

### ISSUE THREAD

**Issue by ErykDarnowski** [mattlqx/pre-commit-search-and-replace#11]
Hey!

After using the [cSpell](https://github.com/streetsidesoftware/cspell-cli) **pre-commit** hook I've noticed how clear and helpful the colored / highlighted output was:

![Screenshot_20221229_183058](https://user-images.githubusercontent.com/81530705/209988601-f0dd35e1-a3a9-4c6e-876c-47bebf8ff26e.png)

This made me look through **search-and-replace**'s README but I couldn't find any flag that would achieve that.

That's why I wrote this issue, or rather a feature request.
Also, unfortunately because I'm not familiar with *Ruby*, I most likely won't be able to work on this myself!

**Comment by mattlqx** [comment]
Added in `v1.1.0`. Thanks for the suggestion.
