### ISSUE TITLE
Using the latest version 1.1.0, we are getting this error 'cannot load such file -- rainbow (LoadError)'

### ISSUE THREAD

**Issue by dmundra** [mattlqx/pre-commit-search-and-replace#17]
The error can be seen here https://results.pre-commit.ci/run/github/69914976/1712958503.da6e95QuTOS2OgqthYnttw. I am not sure why pre-commit is having an issue. Is it the version of ruby?

**Comment by mattlqx** [comment]
Should be good to go now in v1.1.2. I didn't it set up properly for gem dependencies.
