### ISSUE TITLE
Enable passing multiline option to regex

### ISSUE THREAD

**Issue by cbachhuber** [mattlqx/pre-commit-search-and-replace#25]
To enable regex, the [config requires the search string to start and end with `/`](https://github.com/mattlqx/pre-commit-search-and-replace/blob/7e44c73ee8b57d7d909e5ee4bbcd4ef7e3d11a12/README.md#usage). However, [ruby regexes pass options after the end delimiter](https://ruby-doc.org/core-2.4.2/Regexp.html#class-Regexp-label-Options), so that's conflicting. I can reproduce this with the following `.pre-commit-search-and-replace.yaml`:

```yaml
- search: /a+/
  replacement: ""
```

matches a file such as

```text
aaaa
```

while

```yaml
- search: /a+/m
  replacement: ""
```

doesn't match, since this is not seen as regex per [this line](https://github.com/mattlqx/pre-commit-search-and-replace/blob/7e44c73ee8b57d7d909e5ee4bbcd4ef7e3d11a12/lib/search-and-replace.rb#L28). 

How should we best implement this? Provide another command line argument, similar to `--insensitive`? I tried that, but it doesn't seem to work as `search_opts: "--insensitive"` in `.pre-commit-search-and-replace.yaml` or `args: ["--insensitive"]` in `.pre-commit-config.yaml`.

**Comment by cbachhuber** [comment]
Since there are only 4 options in ruby regex, I suggest extending the matcher in [this line](https://github.com/mattlqx/pre-commit-search-and-replace/blob/7e44c73ee8b57d7d909e5ee4bbcd4ef7e3d11a12/lib/search-and-replace.rb#L28) to something like

```ruby
    !%r{^/.*/([imxo]){0,4}$}.match(string).nil?
```

and correspondingly passing on the provided options to the regex object.

**Comment by mattlqx** [comment]
Lines are matched one by one so I'm not sure multi-line would work without a refactor.

**Comment by cbachhuber** [comment]
Got it. Do you want to refactor or should we document that this hook is intended for single-line matches only?

**Comment by mattlqx** [comment]
The whole thing would need refactored, so no I would not be itching to do that. Happy to add a doc though.

**Comment by cbachhuber** [comment]
I should've read the readme more closely, it's already mentioned [here](https://github.com/mattlqx/pre-commit-search-and-replace/blob/807f611aab66a5a3cc38f9d2eb4f121344cd7391/README.md?plain=1#L3).
