### ISSUE TITLE
Updating to version v1.1.5 is failing in pre-commit.ci

### ISSUE THREAD

**Issue by dmundra** [mattlqx/pre-commit-search-and-replace#28]
Our repos received an automatic PR https://github.com/CivicActions/accessibility/pull/788 to update the version but the builds are failing https://results.pre-commit.ci/run/github/316053458/1727727747.JiPsq-u4SsuaRuDbbggntw

Is there an issue or a missing configuration we need to do?

**Comment by mattlqx** [comment]
https://github.com/mattlqx/pre-commit-search-and-replace/pull/27 added a language version to the config to correct a potential issue with the environment missing executables. As a result, on first use pre-commit is going to build the version of Ruby specified. That certainly exceeds the timeout of 2m that that test has. Try upping the timeout if you can, or [overriding it by adding](https://pre-commit.com/#overriding-language-version) `language_version: default` to your config.

**Comment by dmundra** [comment]
Ah thank you. Using `language_version: default` worked.

**Comment by mattlqx** [comment]
Great!
