### ISSUE TITLE
Bump language version to an actively maintaned ruby version

### ISSUE THREAD

**Issue by hofbi** [mattlqx/pre-commit-search-and-replace#29]
@cbachhuber  @mattlqx FYI, this does not work with pre-commit.ci since 2.7 is already EOL and pre-commit.ci does not support unmaintained language versions. My recommendation would be to update to 3.2 according to https://www.ruby-lang.org/en/downloads/branches/

_Originally posted by @hofbi in https://github.com/mattlqx/pre-commit-search-and-replace/pull/27#discussion_r1809068090_

**Comment by mattlqx** [comment]
Updated, thanks.
