### ISSUE TITLE
Add a file argument to run searches only on specific files

### ISSUE THREAD

**Issue by mildblimp** [mattlqx/pre-commit-search-and-replace#7]
This can be helpful if the string is common but should be disallowed in a particular file.

**Comment by mattlqx** [comment]
This is actually native to pre-commit itself. In the `.pre-commit-hooks.yaml` config where you're activating the hook, you can use [`exclude:`](https://pre-commit.com/#config-exclude) to exclude a list of files. There's a good example of this w/ regex [here](https://pre-commit.com/#regular-expressions).

**Comment by mildblimp** [comment]
Ah of course! You are totally right, my apologies.
